version: '3'
networks:
  internal:
    driver: bridge
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    networks:
      - internal
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: snippetbox
    volumes:
      - db-data:/var/lib/postgresql/data
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   networks:
  #     - internal
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: admin
  #     DB_PASSWORD: admin
  #     DB_NAME: snippetbox
  #     PORT: ":8080"
volumes:
  db-data: